MEDIAHAVEN_API=$MEDIAHAVEN_API \
MEDIAHAVEN_USER=$MEDIAHAVEN_USER \
MEDIAHAVEN_PASS=$MEDIAHAVEN_PASS \
REDIS_URL=redis://127.0.0.1:6379/0 REDIS_EXPIRE=20 \
bundle exec sidekiq -r ./app.rb -C config/sidekiq.yml

