apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "web-app"
  name: "s3-proxy"
  labels:
    app: "s3-proxy"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "s3-proxy-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-proxy"
        app.kubernetes.io/component: "s3-proxy-${env}"
        app.kubernetes.io/instance: "s3-proxy-${env}"
        app.kubernetes.io/name: "s3-proxy"
        app.kubernetes.io/part-of: "s3-proxy"
        app.openshift.io/runtime: "s3-proxy"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "s3-proxy-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "s3-proxy-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-proxy"
        app.kubernetes.io/component: "s3-proxy-${env}"
        app.kubernetes.io/instance: "s3-proxy-${env}"
        app.kubernetes.io/name: "s3-proxy"
        app.kubernetes.io/part-of: "s3-proxy"
        app.openshift.io/runtime: "s3-proxy"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "s3-proxy-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "s3-proxy-${env}"
            deploymentconfig: "s3-proxy-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "s3-proxy-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "s3-proxy-${env}"
                - secretRef:
                    name: "s3-proxy-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/s3-components/s3-proxy:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "s3-proxy-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-proxy"
        app.kubernetes.io/component: "s3-proxy-${env}"
        app.kubernetes.io/instance: "s3-proxy-${env}"
        app.kubernetes.io/name: "s3-proxy"
        app.kubernetes.io/part-of: "s3-proxy"
        app.openshift.io/runtime: "s3-proxy"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      MEDIAHAVEN_API: some_value
      PORT: some_value
      WORKERS: some_value
      S3_SERVER: some_value
      TENANT_API: some_value
      EXPORT_LOCATION_ID: some_value
      STATUS_POLL_INTERVAL: some_value
      STATUS_MAX_POLL_COUNT: some_value
      MEDIAHAVEN_SWARM: some_value
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "s3-proxy-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-proxy"
        app.kubernetes.io/component: "s3-proxy-${env}"
        app.kubernetes.io/instance: "s3-proxy-${env}"
        app.kubernetes.io/name: "s3-proxy"
        app.kubernetes.io/part-of: "s3-proxy"
        app.openshift.io/runtime: "s3-proxy"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    stringData:
      REDIS_URL: ''
      MEDIAHAVEN_USER: ''
      MEDIAHAVEN_PASS: ''
      TENANT_USER: ''
      TENANT_PASS: ''
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "512"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"